/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface {
	AddElem(http.ResponseWriter, *http.Request)
	AddWine(http.ResponseWriter, *http.Request)
	Authorize(http.ResponseWriter, *http.Request)
	CreateElem(http.ResponseWriter, *http.Request)
	CreateUserWine(http.ResponseWriter, *http.Request)
	DecreaseElem(http.ResponseWriter, *http.Request)
	DeleteElem(http.ResponseWriter, *http.Request)
	DeleteUserWine(http.ResponseWriter, *http.Request)
	DeleteWine(http.ResponseWriter, *http.Request)
	GetByOrder(http.ResponseWriter, *http.Request)
	GetOrder(http.ResponseWriter, *http.Request)
	GetOrderByUser(http.ResponseWriter, *http.Request)
	GetUser(http.ResponseWriter, *http.Request)
	GetUserWines(http.ResponseWriter, *http.Request)
	GetWine(http.ResponseWriter, *http.Request)
	GetWines(http.ResponseWriter, *http.Request)
	PayBill(http.ResponseWriter, *http.Request)
	PlaceOrder(http.ResponseWriter, *http.Request)
	Register(http.ResponseWriter, *http.Request)
	UpdatePoints(http.ResponseWriter, *http.Request)
	UpdateWine(http.ResponseWriter, *http.Request)
}

// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface {
	AddElem(context.Context, string) (ImplResponse, error)
	AddWine(context.Context, AddWineRequest) (ImplResponse, error)
	Authorize(context.Context, AuthRequest) (ImplResponse, error)
	CreateElem(context.Context, CreateElemRequest) (ImplResponse, error)
	CreateUserWine(context.Context, UserWine) (ImplResponse, error)
	DecreaseElem(context.Context, string) (ImplResponse, error)
	DeleteElem(context.Context, string) (ImplResponse, error)
	DeleteUserWine(context.Context, UserWine) (ImplResponse, error)
	DeleteWine(context.Context, string) (ImplResponse, error)
	GetByOrder(context.Context, GetByOrderRequest) (ImplResponse, error)
	GetOrder(context.Context, string) (ImplResponse, error)
	GetOrderByUser(context.Context, GetOrderByUserRequest) (ImplResponse, error)
	GetUser(context.Context, string) (ImplResponse, error)
	GetUserWines(context.Context, string) (ImplResponse, error)
	GetWine(context.Context, string) (ImplResponse, error)
	GetWines(context.Context, GetWinesRequest) (ImplResponse, error)
	PayBill(context.Context, string) (ImplResponse, error)
	PlaceOrder(context.Context, Order) (ImplResponse, error)
	Register(context.Context, RegisterRequest) (ImplResponse, error)
	UpdatePoints(context.Context, UpdatePointsRequest) (ImplResponse, error)
	UpdateWine(context.Context, Wine) (ImplResponse, error)
}
