/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserWines struct {
	UserWines []UserWine `json:"userWines"`
}

// AssertUserWinesRequired checks if the required fields are not zero-ed
func AssertUserWinesRequired(obj UserWines) error {
	elements := map[string]interface{}{
		"userWines": obj.UserWines,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.UserWines {
		if err := AssertUserWineRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertUserWinesConstraints checks if the values respects the defined constraints
func AssertUserWinesConstraints(obj UserWines) error {
	return nil
}
