/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {
	Id string `json:"id"`

	Login string `json:"login"`

	Password string `json:"password"`

	Fio string `json:"fio"`

	Email string `json:"email"`

	Points string `json:"points"`

	Status string `json:"status"`

	CntFavourites string `json:"cntFavourites"`
}

// AssertUserRequired checks if the required fields are not zero-ed
func AssertUserRequired(obj User) error {
	elements := map[string]interface{}{
		"id":            obj.Id,
		"login":         obj.Login,
		"password":      obj.Password,
		"fio":           obj.Fio,
		"email":         obj.Email,
		"points":        obj.Points,
		"status":        obj.Status,
		"cntFavourites": obj.CntFavourites,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserConstraints checks if the values respects the defined constraints
func AssertUserConstraints(obj User) error {
	return nil
}
