/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Elems struct {
	Elems []Elem `json:"elems"`
}

// AssertElemsRequired checks if the required fields are not zero-ed
func AssertElemsRequired(obj Elems) error {
	elements := map[string]interface{}{
		"elems": obj.Elems,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Elems {
		if err := AssertElemRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertElemsConstraints checks if the values respects the defined constraints
func AssertElemsConstraints(obj Elems) error {
	return nil
}
