/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetWinesRequest struct {
	Limit string `json:"limit"`

	Skip string `json:"skip"`
}

// AssertGetWinesRequestRequired checks if the required fields are not zero-ed
func AssertGetWinesRequestRequired(obj GetWinesRequest) error {
	elements := map[string]interface{}{
		"limit": obj.Limit,
		"skip":  obj.Skip,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertGetWinesRequestConstraints checks if the values respects the defined constraints
func AssertGetWinesRequestConstraints(obj GetWinesRequest) error {
	return nil
}
