/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeleteUserWineResponse struct {
	Deleted bool `json:"deleted"`
}

// AssertDeleteUserWineResponseRequired checks if the required fields are not zero-ed
func AssertDeleteUserWineResponseRequired(obj DeleteUserWineResponse) error {
	elements := map[string]interface{}{
		"deleted": obj.Deleted,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDeleteUserWineResponseConstraints checks if the values respects the defined constraints
func AssertDeleteUserWineResponseConstraints(obj DeleteUserWineResponse) error {
	return nil
}
