/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdateWineResponse struct {
	Updated bool `json:"updated"`
}

// AssertUpdateWineResponseRequired checks if the required fields are not zero-ed
func AssertUpdateWineResponseRequired(obj UpdateWineResponse) error {
	elements := map[string]interface{}{
		"updated": obj.Updated,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUpdateWineResponseConstraints checks if the values respects the defined constraints
func AssertUpdateWineResponseConstraints(obj UpdateWineResponse) error {
	return nil
}
