/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserWine struct {
	IdUser string `json:"idUser"`

	IdWine string `json:"idWine"`
}

// AssertUserWineRequired checks if the required fields are not zero-ed
func AssertUserWineRequired(obj UserWine) error {
	elements := map[string]interface{}{
		"idUser": obj.IdUser,
		"idWine": obj.IdWine,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserWineConstraints checks if the values respects the defined constraints
func AssertUserWineConstraints(obj UserWine) error {
	return nil
}
