/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdatePointsRequest struct {
	Id string `json:"id"`

	Points int32 `json:"points"`
}

// AssertUpdatePointsRequestRequired checks if the required fields are not zero-ed
func AssertUpdatePointsRequestRequired(obj UpdatePointsRequest) error {
	elements := map[string]interface{}{
		"id":     obj.Id,
		"points": obj.Points,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUpdatePointsRequestConstraints checks if the values respects the defined constraints
func AssertUpdatePointsRequestConstraints(obj UpdatePointsRequest) error {
	return nil
}
