/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DecreaseElemResponse struct {
	Decreased bool `json:"decreased"`
}

// AssertDecreaseElemResponseRequired checks if the required fields are not zero-ed
func AssertDecreaseElemResponseRequired(obj DecreaseElemResponse) error {
	elements := map[string]interface{}{
		"decreased": obj.Decreased,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDecreaseElemResponseConstraints checks if the values respects the defined constraints
func AssertDecreaseElemResponseConstraints(obj DecreaseElemResponse) error {
	return nil
}
