/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Elem struct {
	Id string `json:"id"`

	IdOrder string `json:"idOrder"`

	IdWine string `json:"idWine"`

	Count int32 `json:"count"`
}

// AssertElemRequired checks if the required fields are not zero-ed
func AssertElemRequired(obj Elem) error {
	elements := map[string]interface{}{
		"id":      obj.Id,
		"idOrder": obj.IdOrder,
		"idWine":  obj.IdWine,
		"count":   obj.Count,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertElemConstraints checks if the values respects the defined constraints
func AssertElemConstraints(obj Elem) error {
	return nil
}
