/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AuthRequest struct {
	Login string `json:"login"`

	Password string `json:"password"`
}

// AssertAuthRequestRequired checks if the required fields are not zero-ed
func AssertAuthRequestRequired(obj AuthRequest) error {
	elements := map[string]interface{}{
		"login":    obj.Login,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAuthRequestConstraints checks if the values respects the defined constraints
func AssertAuthRequestConstraints(obj AuthRequest) error {
	return nil
}
