/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AddWineRequest struct {
	Name string `json:"name"`

	Count string `json:"count"`

	Year int32 `json:"year"`

	Strength int32 `json:"strength"`

	Price string `json:"price"`

	Type string `json:"type"`
}

// AssertAddWineRequestRequired checks if the required fields are not zero-ed
func AssertAddWineRequestRequired(obj AddWineRequest) error {
	elements := map[string]interface{}{
		"name":     obj.Name,
		"count":    obj.Count,
		"year":     obj.Year,
		"strength": obj.Strength,
		"price":    obj.Price,
		"type":     obj.Type,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAddWineRequestConstraints checks if the values respects the defined constraints
func AssertAddWineRequestConstraints(obj AddWineRequest) error {
	return nil
}
