/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RegisterResponse struct {
	Registered bool `json:"registered"`
}

// AssertRegisterResponseRequired checks if the required fields are not zero-ed
func AssertRegisterResponseRequired(obj RegisterResponse) error {
	elements := map[string]interface{}{
		"registered": obj.Registered,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegisterResponseConstraints checks if the values respects the defined constraints
func AssertRegisterResponseConstraints(obj RegisterResponse) error {
	return nil
}
