/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PayBillResponse struct {
	Payed bool `json:"payed"`
}

// AssertPayBillResponseRequired checks if the required fields are not zero-ed
func AssertPayBillResponseRequired(obj PayBillResponse) error {
	elements := map[string]interface{}{
		"payed": obj.Payed,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPayBillResponseConstraints checks if the values respects the defined constraints
func AssertPayBillResponseConstraints(obj PayBillResponse) error {
	return nil
}
