/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetWinesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWinesRequest{}

// GetWinesRequest struct for GetWinesRequest
type GetWinesRequest struct {
	Limit string `json:"limit"`
	Skip  string `json:"skip"`
}

// NewGetWinesRequest instantiates a new GetWinesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWinesRequest(limit string, skip string) *GetWinesRequest {
	this := GetWinesRequest{}
	this.Limit = limit
	this.Skip = skip
	return &this
}

// NewGetWinesRequestWithDefaults instantiates a new GetWinesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWinesRequestWithDefaults() *GetWinesRequest {
	this := GetWinesRequest{}
	return &this
}

// GetLimit returns the Limit field value
func (o *GetWinesRequest) GetLimit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *GetWinesRequest) GetLimitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *GetWinesRequest) SetLimit(v string) {
	o.Limit = v
}

// GetSkip returns the Skip field value
func (o *GetWinesRequest) GetSkip() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Skip
}

// GetSkipOk returns a tuple with the Skip field value
// and a boolean to check if the value has been set.
func (o *GetWinesRequest) GetSkipOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Skip, true
}

// SetSkip sets field value
func (o *GetWinesRequest) SetSkip(v string) {
	o.Skip = v
}

func (o GetWinesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWinesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["limit"] = o.Limit
	toSerialize["skip"] = o.Skip
	return toSerialize, nil
}

type NullableGetWinesRequest struct {
	value *GetWinesRequest
	isSet bool
}

func (v NullableGetWinesRequest) Get() *GetWinesRequest {
	return v.value
}

func (v *NullableGetWinesRequest) Set(val *GetWinesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWinesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWinesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWinesRequest(val *GetWinesRequest) *NullableGetWinesRequest {
	return &NullableGetWinesRequest{value: val, isSet: true}
}

func (v NullableGetWinesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWinesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
