/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderRequest{}

// GetOrderRequest struct for GetOrderRequest
type GetOrderRequest struct {
	Id string `json:"id"`
}

// NewGetOrderRequest instantiates a new GetOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderRequest(id string) *GetOrderRequest {
	this := GetOrderRequest{}
	this.Id = id
	return &this
}

// NewGetOrderRequestWithDefaults instantiates a new GetOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderRequestWithDefaults() *GetOrderRequest {
	this := GetOrderRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GetOrderRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetOrderRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetOrderRequest) SetId(v string) {
	o.Id = v
}

func (o GetOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGetOrderRequest struct {
	value *GetOrderRequest
	isSet bool
}

func (v NullableGetOrderRequest) Get() *GetOrderRequest {
	return v.value
}

func (v *NullableGetOrderRequest) Set(val *GetOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderRequest(val *GetOrderRequest) *NullableGetOrderRequest {
	return &NullableGetOrderRequest{value: val, isSet: true}
}

func (v NullableGetOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
