/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AddElemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddElemRequest{}

// AddElemRequest struct for AddElemRequest
type AddElemRequest struct {
	Id string `json:"id"`
}

// NewAddElemRequest instantiates a new AddElemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddElemRequest(id string) *AddElemRequest {
	this := AddElemRequest{}
	this.Id = id
	return &this
}

// NewAddElemRequestWithDefaults instantiates a new AddElemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddElemRequestWithDefaults() *AddElemRequest {
	this := AddElemRequest{}
	return &this
}

// GetId returns the Id field value
func (o *AddElemRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AddElemRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AddElemRequest) SetId(v string) {
	o.Id = v
}

func (o AddElemRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddElemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableAddElemRequest struct {
	value *AddElemRequest
	isSet bool
}

func (v NullableAddElemRequest) Get() *AddElemRequest {
	return v.value
}

func (v *NullableAddElemRequest) Set(val *AddElemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddElemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddElemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddElemRequest(val *AddElemRequest) *NullableAddElemRequest {
	return &NullableAddElemRequest{value: val, isSet: true}
}

func (v NullableAddElemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddElemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
