/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AddWineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddWineResponse{}

// AddWineResponse struct for AddWineResponse
type AddWineResponse struct {
	Added bool `json:"added"`
}

// NewAddWineResponse instantiates a new AddWineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddWineResponse(added bool) *AddWineResponse {
	this := AddWineResponse{}
	this.Added = added
	return &this
}

// NewAddWineResponseWithDefaults instantiates a new AddWineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddWineResponseWithDefaults() *AddWineResponse {
	this := AddWineResponse{}
	return &this
}

// GetAdded returns the Added field value
func (o *AddWineResponse) GetAdded() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Added
}

// GetAddedOk returns a tuple with the Added field value
// and a boolean to check if the value has been set.
func (o *AddWineResponse) GetAddedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Added, true
}

// SetAdded sets field value
func (o *AddWineResponse) SetAdded(v bool) {
	o.Added = v
}

func (o AddWineResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddWineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["added"] = o.Added
	return toSerialize, nil
}

type NullableAddWineResponse struct {
	value *AddWineResponse
	isSet bool
}

func (v NullableAddWineResponse) Get() *AddWineResponse {
	return v.value
}

func (v *NullableAddWineResponse) Set(val *AddWineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddWineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddWineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddWineResponse(val *AddWineResponse) *NullableAddWineResponse {
	return &NullableAddWineResponse{value: val, isSet: true}
}

func (v NullableAddWineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddWineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
