/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DecreaseElemRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecreaseElemRequest{}

// DecreaseElemRequest struct for DecreaseElemRequest
type DecreaseElemRequest struct {
	Id string `json:"id"`
}

// NewDecreaseElemRequest instantiates a new DecreaseElemRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecreaseElemRequest(id string) *DecreaseElemRequest {
	this := DecreaseElemRequest{}
	this.Id = id
	return &this
}

// NewDecreaseElemRequestWithDefaults instantiates a new DecreaseElemRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecreaseElemRequestWithDefaults() *DecreaseElemRequest {
	this := DecreaseElemRequest{}
	return &this
}

// GetId returns the Id field value
func (o *DecreaseElemRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DecreaseElemRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DecreaseElemRequest) SetId(v string) {
	o.Id = v
}

func (o DecreaseElemRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecreaseElemRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableDecreaseElemRequest struct {
	value *DecreaseElemRequest
	isSet bool
}

func (v NullableDecreaseElemRequest) Get() *DecreaseElemRequest {
	return v.value
}

func (v *NullableDecreaseElemRequest) Set(val *DecreaseElemRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDecreaseElemRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDecreaseElemRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecreaseElemRequest(val *DecreaseElemRequest) *NullableDecreaseElemRequest {
	return &NullableDecreaseElemRequest{value: val, isSet: true}
}

func (v NullableDecreaseElemRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecreaseElemRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
