/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteWineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteWineResponse{}

// DeleteWineResponse struct for DeleteWineResponse
type DeleteWineResponse struct {
	Deleted bool `json:"deleted"`
}

// NewDeleteWineResponse instantiates a new DeleteWineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteWineResponse(deleted bool) *DeleteWineResponse {
	this := DeleteWineResponse{}
	this.Deleted = deleted
	return &this
}

// NewDeleteWineResponseWithDefaults instantiates a new DeleteWineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteWineResponseWithDefaults() *DeleteWineResponse {
	this := DeleteWineResponse{}
	return &this
}

// GetDeleted returns the Deleted field value
func (o *DeleteWineResponse) GetDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value
// and a boolean to check if the value has been set.
func (o *DeleteWineResponse) GetDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deleted, true
}

// SetDeleted sets field value
func (o *DeleteWineResponse) SetDeleted(v bool) {
	o.Deleted = v
}

func (o DeleteWineResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteWineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deleted"] = o.Deleted
	return toSerialize, nil
}

type NullableDeleteWineResponse struct {
	value *DeleteWineResponse
	isSet bool
}

func (v NullableDeleteWineResponse) Get() *DeleteWineResponse {
	return v.value
}

func (v *NullableDeleteWineResponse) Set(val *DeleteWineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteWineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteWineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteWineResponse(val *DeleteWineResponse) *NullableDeleteWineResponse {
	return &NullableDeleteWineResponse{value: val, isSet: true}
}

func (v NullableDeleteWineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteWineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
