/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateElemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateElemResponse{}

// CreateElemResponse struct for CreateElemResponse
type CreateElemResponse struct {
	Created bool `json:"created"`
}

// NewCreateElemResponse instantiates a new CreateElemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateElemResponse(created bool) *CreateElemResponse {
	this := CreateElemResponse{}
	this.Created = created
	return &this
}

// NewCreateElemResponseWithDefaults instantiates a new CreateElemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateElemResponseWithDefaults() *CreateElemResponse {
	this := CreateElemResponse{}
	return &this
}

// GetCreated returns the Created field value
func (o *CreateElemResponse) GetCreated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *CreateElemResponse) GetCreatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *CreateElemResponse) SetCreated(v bool) {
	o.Created = v
}

func (o CreateElemResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateElemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	return toSerialize, nil
}

type NullableCreateElemResponse struct {
	value *CreateElemResponse
	isSet bool
}

func (v NullableCreateElemResponse) Get() *CreateElemResponse {
	return v.value
}

func (v *NullableCreateElemResponse) Set(val *CreateElemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateElemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateElemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateElemResponse(val *CreateElemResponse) *NullableCreateElemResponse {
	return &NullableCreateElemResponse{value: val, isSet: true}
}

func (v NullableCreateElemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateElemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
