/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdatePointsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePointsRequest{}

// UpdatePointsRequest struct for UpdatePointsRequest
type UpdatePointsRequest struct {
	Id     string `json:"id"`
	Points int32  `json:"points"`
}

// NewUpdatePointsRequest instantiates a new UpdatePointsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePointsRequest(id string, points int32) *UpdatePointsRequest {
	this := UpdatePointsRequest{}
	this.Id = id
	this.Points = points
	return &this
}

// NewUpdatePointsRequestWithDefaults instantiates a new UpdatePointsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePointsRequestWithDefaults() *UpdatePointsRequest {
	this := UpdatePointsRequest{}
	return &this
}

// GetId returns the Id field value
func (o *UpdatePointsRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdatePointsRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdatePointsRequest) SetId(v string) {
	o.Id = v
}

// GetPoints returns the Points field value
func (o *UpdatePointsRequest) GetPoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *UpdatePointsRequest) GetPointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Points, true
}

// SetPoints sets field value
func (o *UpdatePointsRequest) SetPoints(v int32) {
	o.Points = v
}

func (o UpdatePointsRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePointsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["points"] = o.Points
	return toSerialize, nil
}

type NullableUpdatePointsRequest struct {
	value *UpdatePointsRequest
	isSet bool
}

func (v NullableUpdatePointsRequest) Get() *UpdatePointsRequest {
	return v.value
}

func (v *NullableUpdatePointsRequest) Set(val *UpdatePointsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePointsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePointsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePointsRequest(val *UpdatePointsRequest) *NullableUpdatePointsRequest {
	return &NullableUpdatePointsRequest{value: val, isSet: true}
}

func (v NullableUpdatePointsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePointsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
