/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOrderByUserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrderByUserRequest{}

// GetOrderByUserRequest struct for GetOrderByUserRequest
type GetOrderByUserRequest struct {
	Id string `json:"id"`
}

// NewGetOrderByUserRequest instantiates a new GetOrderByUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrderByUserRequest(id string) *GetOrderByUserRequest {
	this := GetOrderByUserRequest{}
	this.Id = id
	return &this
}

// NewGetOrderByUserRequestWithDefaults instantiates a new GetOrderByUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrderByUserRequestWithDefaults() *GetOrderByUserRequest {
	this := GetOrderByUserRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GetOrderByUserRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetOrderByUserRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetOrderByUserRequest) SetId(v string) {
	o.Id = v
}

func (o GetOrderByUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrderByUserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

type NullableGetOrderByUserRequest struct {
	value *GetOrderByUserRequest
	isSet bool
}

func (v NullableGetOrderByUserRequest) Get() *GetOrderByUserRequest {
	return v.value
}

func (v *NullableGetOrderByUserRequest) Set(val *GetOrderByUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrderByUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrderByUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrderByUserRequest(val *GetOrderByUserRequest) *NullableGetOrderByUserRequest {
	return &NullableGetOrderByUserRequest{value: val, isSet: true}
}

func (v NullableGetOrderByUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrderByUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
