/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetWinesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWinesResponse{}

// GetWinesResponse struct for GetWinesResponse
type GetWinesResponse struct {
	Wines []Wine `json:"wines"`
}

// NewGetWinesResponse instantiates a new GetWinesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWinesResponse(wines []Wine) *GetWinesResponse {
	this := GetWinesResponse{}
	this.Wines = wines
	return &this
}

// NewGetWinesResponseWithDefaults instantiates a new GetWinesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWinesResponseWithDefaults() *GetWinesResponse {
	this := GetWinesResponse{}
	return &this
}

// GetWines returns the Wines field value
func (o *GetWinesResponse) GetWines() []Wine {
	if o == nil {
		var ret []Wine
		return ret
	}

	return o.Wines
}

// GetWinesOk returns a tuple with the Wines field value
// and a boolean to check if the value has been set.
func (o *GetWinesResponse) GetWinesOk() ([]Wine, bool) {
	if o == nil {
		return nil, false
	}
	return o.Wines, true
}

// SetWines sets field value
func (o *GetWinesResponse) SetWines(v []Wine) {
	o.Wines = v
}

func (o GetWinesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWinesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["wines"] = o.Wines
	return toSerialize, nil
}

type NullableGetWinesResponse struct {
	value *GetWinesResponse
	isSet bool
}

func (v NullableGetWinesResponse) Get() *GetWinesResponse {
	return v.value
}

func (v *NullableGetWinesResponse) Set(val *GetWinesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWinesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWinesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWinesResponse(val *GetWinesResponse) *NullableGetWinesResponse {
	return &NullableGetWinesResponse{value: val, isSet: true}
}

func (v NullableGetWinesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWinesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
