/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateWineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateWineResponse{}

// UpdateWineResponse struct for UpdateWineResponse
type UpdateWineResponse struct {
	Updated bool `json:"updated"`
}

// NewUpdateWineResponse instantiates a new UpdateWineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateWineResponse(updated bool) *UpdateWineResponse {
	this := UpdateWineResponse{}
	this.Updated = updated
	return &this
}

// NewUpdateWineResponseWithDefaults instantiates a new UpdateWineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateWineResponseWithDefaults() *UpdateWineResponse {
	this := UpdateWineResponse{}
	return &this
}

// GetUpdated returns the Updated field value
func (o *UpdateWineResponse) GetUpdated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *UpdateWineResponse) GetUpdatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *UpdateWineResponse) SetUpdated(v bool) {
	o.Updated = v
}

func (o UpdateWineResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateWineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

type NullableUpdateWineResponse struct {
	value *UpdateWineResponse
	isSet bool
}

func (v NullableUpdateWineResponse) Get() *UpdateWineResponse {
	return v.value
}

func (v *NullableUpdateWineResponse) Set(val *UpdateWineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateWineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateWineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateWineResponse(val *UpdateWineResponse) *NullableUpdateWineResponse {
	return &NullableUpdateWineResponse{value: val, isSet: true}
}

func (v NullableUpdateWineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateWineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
