/*
API for ppo project

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DecreaseElemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DecreaseElemResponse{}

// DecreaseElemResponse struct for DecreaseElemResponse
type DecreaseElemResponse struct {
	Decreased bool `json:"decreased"`
}

// NewDecreaseElemResponse instantiates a new DecreaseElemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecreaseElemResponse(decreased bool) *DecreaseElemResponse {
	this := DecreaseElemResponse{}
	this.Decreased = decreased
	return &this
}

// NewDecreaseElemResponseWithDefaults instantiates a new DecreaseElemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecreaseElemResponseWithDefaults() *DecreaseElemResponse {
	this := DecreaseElemResponse{}
	return &this
}

// GetDecreased returns the Decreased field value
func (o *DecreaseElemResponse) GetDecreased() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Decreased
}

// GetDecreasedOk returns a tuple with the Decreased field value
// and a boolean to check if the value has been set.
func (o *DecreaseElemResponse) GetDecreasedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decreased, true
}

// SetDecreased sets field value
func (o *DecreaseElemResponse) SetDecreased(v bool) {
	o.Decreased = v
}

func (o DecreaseElemResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DecreaseElemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["decreased"] = o.Decreased
	return toSerialize, nil
}

type NullableDecreaseElemResponse struct {
	value *DecreaseElemResponse
	isSet bool
}

func (v NullableDecreaseElemResponse) Get() *DecreaseElemResponse {
	return v.value
}

func (v *NullableDecreaseElemResponse) Set(val *DecreaseElemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDecreaseElemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDecreaseElemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecreaseElemResponse(val *DecreaseElemResponse) *NullableDecreaseElemResponse {
	return &NullableDecreaseElemResponse{value: val, isSet: true}
}

func (v NullableDecreaseElemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecreaseElemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
